const TZ="America/Sao_Paulo";
let DATA=null,filter="agora",query="";
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const norm=s=>(s||"").toString().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const isBrazil=m=>norm(m.home)==="brasil"||norm(m.away)==="brasil";
const dt=m=>new Date(m.utcDate||m.date);
const todayKey=()=>new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const dateKey=d=>new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).format(d);
const fmtDate=d=>new Intl.DateTimeFormat("pt-BR",{timeZone:TZ,weekday:"short",day:"2-digit",month:"short"}).format(d).replace(".","");
const fmtTime=d=>new Intl.DateTimeFormat("pt-BR",{timeZone:TZ,hour:"2-digit",minute:"2-digit"}).format(d);
const finished=m=>["FT","AET","PEN","CANC","ABD"].includes(m.statusShort)||m.status==="finished";
const live=m=>["1H","HT","2H","ET","P","BT","LIVE"].includes(m.statusShort)||m.status==="live";
const upcoming=m=>!finished(m)&&!live(m);
const stageLabel=s=>({grupos:"Fase de grupos",round32:"16 avos",oitavas:"Oitavas",quartas:"Quartas",semifinal:"Semifinal",terceiro:"3º lugar",final:"Final"}[s]||s||"Jogo");
const statusLabel=m=>live(m)?"Ao vivo":finished(m)?"Encerrado":dateKey(dt(m))===todayKey()?"Hoje":"Próximo";
const score=m=>finished(m)||live(m)?`<span class="score">${m.homeScore??""}</span>`:"";
function sortMatches(a,b){return dt(a)-dt(b)}
function matchCard(m){const d=dt(m);const cls=`match-card ${isBrazil(m)?"brazil":""}`;const tags=[];if(finished(m))tags.push(`<span class="tag official">Resultado oficial</span>`);if(m.projection)tags.push(`<span class="tag projection">Projeção: ${m.projection}</span>`);if(m.favorite)tags.push(`<span class="tag">Favorito: ${m.favorite}</span>`);return `<article class="${cls}"><div class="match-top"><div class="match-date">${fmtDate(d)} · ${fmtTime(d)} · Brasília</div><div class="status ${live(m)?"live":finished(m)?"done":""}">${statusLabel(m)}</div></div><div class="team"><span>⚽</span><span>${m.home}</span>${score(m)}</div><div class="team"><span>⚽</span><span>${m.away}</span>${finished(m)||live(m)?`<span class="score">${m.awayScore??""}</span>`:""}</div><div class="stage">${stageLabel(m.stage)}${m.venue?` · ${m.venue}`:""}</div>${tags.length?`<div class="tags">${tags.join("")}</div>`:""}</article>`}
function filteredMatches(){let list=[...(DATA.matches||[])].sort(sortMatches);if(query){const q=norm(query);list=list.filter(m=>norm(`${m.home} ${m.away}`).includes(q))}if(filter==="hoje")list=list.filter(m=>dateKey(dt(m))===todayKey());else if(filter==="proximos")list=list.filter(upcoming).slice(0,12);else if(filter==="resultados")list=list.filter(finished).reverse().slice(0,12);else if(filter==="brasil")list=list.filter(isBrazil);else if(filter==="agora"){const liveNow=list.filter(live);const today=list.filter(m=>dateKey(dt(m))===todayKey()&&!finished(m));list=liveNow.length?liveNow:today.length?today:list.filter(upcoming).slice(0,4)}return list}
function renderMatches(){const list=filteredMatches();$("#matchesList").innerHTML=list.length?list.map(matchCard).join(""):`<div class="empty">Nenhum jogo encontrado neste filtro.</div>`;$$('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}
function renderSummary(){const matches=[...(DATA.matches||[])].sort(sortMatches);const liveNow=matches.filter(live);const today=matches.filter(m=>dateKey(dt(m))===todayKey());const next=matches.find(upcoming);const last=[...matches].filter(finished).sort((a,b)=>dt(b)-dt(a))[0];const brNext=matches.find(m=>isBrazil(m)&&upcoming(m));const top=(DATA.scorers||[])[0];const cards=[liveNow.length?["Agora",`${liveNow.length} jogo(s) ao vivo`,"Acompanhe placar e status em tempo real."]:today.length?["Hoje",`${today.length} jogo(s) no dia`,"Horários em Brasília."]:next?["Próximo jogo",`${next.home} x ${next.away}`,`${fmtDate(dt(next))} · ${fmtTime(dt(next))}`]:["Agenda","Sem jogo iminente","Veja próximos confrontos."],brNext?["Brasil",`${brNext.home} x ${brNext.away}`,`${stageLabel(brNext.stage)} · ${fmtDate(dt(brNext))} às ${fmtTime(dt(brNext))}`]:last?["Último resultado",`${last.home} ${last.homeScore} x ${last.awayScore} ${last.away}`,stageLabel(last.stage)]:["Brasil","Sem próximo jogo definido","Aguardando atualização."],top?["Artilharia",`${top.name}`,`${top.team} · ${top.goals} gols`]:["Artilharia","Aguardando dados","Atualiza 3x ao dia."],[(DATA.favorites||[])[0]?.team?"Favorito":"Projeções",(DATA.favorites||[])[0]?.team||"Aguardando",(DATA.favorites||[])[0]?.chance?`${(DATA.favorites||[])[0].chance}% de título`:"Separadas dos resultados oficiais."]];$("#quickSummary").innerHTML=cards.map(c=>`<div class="summary-card"><span>${c[0]}</span><strong>${c[1]}</strong><span>${c[2]}</span></div>`).join("")}
function renderBrazil(){const br=(DATA.matches||[]).filter(isBrazil).sort(sortMatches);const next=br.find(upcoming);const last=[...br].filter(finished).sort((a,b)=>dt(b)-dt(a))[0];const title=(DATA.favorites||[]).find(f=>norm(f.team)==="brasil");const path=(DATA.brazilPath||[]).map(x=>`<div class="bracket-line"><span>${x.phase}</span><strong>${x.value}</strong></div>`).join("");$("#brazilPanel").innerHTML=`<div class="info-card"><span>Próximo jogo</span><strong>${next?`${next.home} x ${next.away}`:"A definir"}</strong><span>${next?`${fmtDate(dt(next))} · ${fmtTime(dt(next))} · Brasília`:"Aguardando vencedor do confronto"}</span></div><div class="info-card"><span>Último jogo</span><strong>${last?`${last.home} ${last.homeScore} x ${last.awayScore} ${last.away}`:"Sem resultado"}</strong><span>${last?stageLabel(last.stage):""}</span></div><div class="info-card"><span>Chance de título</span><strong>${title?`${title.chance}%`:"A calcular"}</strong><span>Projeção, não resultado oficial.</span></div><div class="info-card"><span>Caminho provável</span>${path||"<strong>Aguardando chave</strong>"}</div>`}
function renderBracket(){const groups=DATA.bracket||[];$("#bracketPanel").innerHTML=groups.length?groups.map(g=>`<div class="bracket-row"><h3>${g.phase}</h3>${g.items.map(i=>`<div class="bracket-line"><span>${i.match}</span><strong>${i.status||i.pick||"A definir"}</strong></div>`).join("")}</div>`).join(""):`<div class="empty">Chaveamento ainda não disponível.</div>`}
function renderStats(){const scorers=(DATA.scorers||[]).slice(0,10).map((s,i)=>`<div class="scorer-row"><div class="rank">${i+1}</div><div><strong>${s.name}</strong><div class="muted">${s.team}</div></div><div class="goals">${s.goals}</div></div>`).join("");const fav=(DATA.favorites||[]).slice(0,6).map((f,i)=>`<div class="bracket-line"><span>${i+1}. ${f.team}</span><strong>${f.chance}%</strong></div>`).join("");$("#statsPanel").innerHTML=`<div class="stat-card"><h3>Artilheiros</h3>${scorers||"<p class='muted'>Sem dados.</p>"}</div><div class="stat-card"><h3>Favoritos</h3>${fav||"<p class='muted'>Sem projeções.</p>"}</div>`}
function renderStatus(){const last=DATA.meta?.lastUpdated?new Date(DATA.meta.lastUpdated):null;$("#updatePill").textContent=last?`Atualizado ${fmtDate(last)} · ${fmtTime(last)}`:"Dados carregados";$("#dataStatus").innerHTML=`Fonte: ${DATA.meta?.source||"base local"}. Atualização automática prevista às 07h17, 15h17 e 22h47 de Brasília. Resultados oficiais, projeções e palpites são exibidos separadamente.`}
function renderAll(){renderSummary();renderMatches();renderBrazil();renderBracket();renderStats();renderStatus()}
async function load(){try{const res=await fetch(`data/copa2026.json?v=${Date.now()}`,{cache:"no-store"});DATA=await res.json();renderAll()}catch(e){$("#quickSummary").innerHTML=`<div class="empty">Não foi possível carregar os dados.</div>`;$("#dataStatus").textContent="Erro ao carregar data/copa2026.json."}}
async function disableOldServiceWorker(){if(!('serviceWorker'in navigator))return;try{const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(reg=>reg.unregister()));}catch{}}
$$('.filter-chip').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;renderMatches()}));
$('#teamSearch').addEventListener('input',e=>{query=e.target.value;renderMatches()});
$('#refreshBtn').addEventListener('click',load);
disableOldServiceWorker();
load();
